name: travy
description: Travis mobile app.

version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0
  built_value: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4
  shared_preferences: ^0.4.3
flutter:

  uses-material-design: true
  fonts:
    - family: travyGlyphs
      fonts:
       - asset: assets/fonts/travyGlyphs.ttf
    - family: ReemKufi
      fonts: 
        - asset: assets/fonts/ReemKufi-Regular.ttf
    - family: Roboto
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - logo.png
    - logo2.png
    - travis_eps.eps